# Use the official Node.js image as a base image
FROM node:17

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (or yarn.lock) to the working directory
COPY package*.json ./

# Install dependencies cleanly
RUN npm ci

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port that the app will run on
EXPOSE 2128

# Define the command to run the app
CMD [ "npm", "run", "dev" ]
