name: Deploy to Prod

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for Production
        run: |
          docker build -f Dockerfile.prod -t ${{ secrets.DOCKER_USERNAME }}/port-api-shubhamshings-prod:latest .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/port-api-shubhamshings-prod:latest ${{ secrets.DOCKER_USERNAME }}/port-api-shubhamshings-prod:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/port-api-shubhamshings-prod:latest

      - name: Deploy to staging server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/port-api-shubhamshings-prod
            docker stop port-api-shubhamshings-prod || true
            docker rm port-api-shubhamshings-prod || true
            docker run -d --name port-api-shubhamshings-prod -p 2828:2828 ${{ secrets.DOCKER_USERNAME }}/port-api-shubhamshings-prod
