name: Deploy to Dev

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create environment file
        run: |
          echo "NODE_ENV=development" >> .env
          echo "SERVER_HOST=0.0.0.0" >> .env
          echo "SERVER_PORT=2128" >> .env

          echo "ACCESS_TOKEN_SECRET=abcd" >> .env
          echo "REFRESH_TOKEN_SECRET=qwer" >> .env
          echo "EMAIL_VERIFICATION_SECRET=yuiop" >> .env

          echo "ACCESS_TOKEN_EXPIRY=1800000" >> .env
          echo "REFRESH_TOKEN_EXPIRY=86400000" >> .env

          echo "SMTP_USERNAME=" >> .env 
          echo "SMTP_PASSWORD=" >> .env
          echo "SMTP_HOST=" >> .env
          echo "SMTP_PORT=" >> .env
          echo "SMTP_SSL=" >> .env
          echo "SMTP_SENDER_NAME=" >> .env
          echo "SMTP_FROM_MAIL=" >> .env

          echo "CORS_ALLOWED_ORIGINS=https://port-dev-api.shubhamsinghs.com" >> .env
          echo "LOG_LEVEL=database" >> .env
          echo "LOG_TIME_ZONE=Asia/Kolkata" >> .env

      - name: Create Docker file
        run: |
          echo "FROM node:20" >> Dockerfile
          echo "WORKDIR /usr/src/app" >> Dockerfile
          echo "COPY package*.json ./" >> Dockerfile
          echo "RUN npm ci" >> Dockerfile
          echo "COPY . ." >> Dockerfile
          echo "EXPOSE 2128" >> Dockerfile
          echo "CMD "npm run dev" >> Dockerfile

      - name: Build Docker image for Development
        run: |
          docker build -f ./Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/port-api-shubhamssingh-dev:latest .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/port-api-shubhamssingh-dev:latest ${{ secrets.DOCKER_USERNAME }}/port-api-shubhamssingh-dev:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/port-api-shubhamssingh-dev:latest

      - name: Deploy to staging server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}

          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/port-api-shubhamssingh-dev
            docker stop port-api-shubhamssingh-dev || true
            docker rm port-api-shubhamssingh-dev || true
            docker run -d --name port-api-shubhamssingh-dev -p 2128:2128 ${{ secrets.DOCKER_USERNAME }}/port-api-shubhamssingh-dev
